### ISSUE TITLE
Discrete content encoder example

### ISSUE THREAD

**Issue by yd11111** [bshall/soft-vc#5]
@bshall since this repo gives a simple inference example based on a soft content encoder. Would you give a discrete encoder based inference example? I found some issues when I try to use a discrete encoder. Here is my code:

when it run to mel = acoustic.generate(units).transpose(1, 2)
a dimension mismatch occurred. Looking forward to your suggestions, thanks a lot.

  File "D:\Software-location\Anaconda\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\YoungTown/.cache\torch\hub\bshall_acoustic-model_main\acoustic\model.py", line 23, in generate
    x = self.encoder(x)
  File "D:\Software-location\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\YoungTown/.cache\torch\hub\bshall_acoustic-model_main\acoustic\model.py", line 49, in forward
    x = self.convs(x.transpose(1, 2))
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

~~~
import torch, torchaudio
hubert = torch.hub.load("bshall/hubert:main", "hubert_discrete").cuda()
acoustic = torch.hub.load("bshall/acoustic-model:main", "hubert_discrete").cuda()
hifigan = torch.hub.load("bshall/hifigan:main", "hifigan_hubert_discrete").cuda()

source, sr = torchaudio.load("./huohuo.wav")
source = torchaudio.transforms.Resample(orig_freq=sr, new_freq=16000)(source)
source = source[0].unsqueeze(0).unsqueeze(0).cuda()

with torch.inference_mode():
    units = hubert.units(source)
    mel = acoustic.generate(units).transpose(1, 2)
    target = hifigan(mel)

    target = target.squeeze().cpu()
    target = target.unsqueeze(0).cpu()
    torchaudio.save('./huohuo_new.wav', target, 16000)
~~~

**Comment by bshall** [comment]
Hi @yd11111, to use the discrete content encoder you have to unsqueeze the units

```python
with torch.inference_mode():
    units = hubert.units(source).unsqueeze(0)
    mel = acoustic.generate(units).transpose(1, 2)
    target = hifigan(mel)
```

I'll add this to the `.units()` method to make it cleaner but you can manually add it in for now.

**Comment by yd11111** [comment]
Hi @bshall , I have worked it out and generated some interesting voice converted waves, many thanks for your interesting work.
